### ISSUE TITLE
support adding basic records

### ISSUE THREAD

**Issue by codefromthecrypt** [Netflix/denominator#11]
Routine DNS work in netflix relates to adding records with the same ttl and simple rdata.  For example, most of the time, we are adding `A`, `CNAME`, or `AAAA`, or `NS` values with TTL 3600, and then checking with dig to see if the updates occurred.

Let's make it very easy to add simple records as this can get early feedback on denominator.

Tasks:
- [x] implement `ResourceRecordSetApi.add(ResourceRecordSetApi<?> in)` (issue #36)
- [x] implement `ResourceRecordSetApi.remove(ResourceRecordSetApi<?> in)`(issue #36)
- [x] implement add/remove record for `mock` (issue #36)
- [x] implement add/remove record for `ultradns` (issue #34)
- [x] implement add/remove record for `route53` (issue #33)
- [x] implement add/remove record for `dynect` (issue #35)
- [x] add record using kwargs.  ex. `denominator record -z foo.com add --name hostname.foo.com --type A --rdata 1.2.3.4`
